### ISSUE TITLE
Build fails in python 3.8 virtualenv

### ISSUE THREAD

**Issue by kbuley** [saltstack/pop#61]
conda create -n pop python=3
conda activate pop
pip install pop aiohttp
mkdir poppy
cd poppy
pop-seed poppy
python build.py poppy

Expected:
a binary in dist/poppy

Actual:
`7623 INFO: Building PYZ (ZlibArchive) /Users/kbuley/saltconf/poppy/build/poppy/PYZ-00.pyz
Traceback (most recent call last):
  File "/Users/kbuley/miniconda3/envs/pop/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/kbuley/miniconda3/envs/pop/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 118, in <module>
    run()
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/Users/kbuley/saltconf/poppy/poppy.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/var/folders/hn/tbbfl5yn683cwzrhxx6w7gnjqmbvz_/T/pop_zq4df1r8_venv/lib/python3.8/site-packages/PyInstaller/building/utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)
Executable created in /Users/kbuley/saltconf/poppy/dist/poppy
To create a more portable and fully static binary install run staticx against your new build`

dist/ is empty.

**Comment by thatch45** [comment]
This is a known upstream pyinstaller bug:
https://github.com/pyinstaller/pyinstaller/issues/4311

as soon as we get a new PyInstaller we can update build.py to use it :)

**Comment by thatch45** [comment]
I decided to move the build.py into a new system called pop-build. That system can build with development versions of pyinstaller and, therefore, can build on python 3.8
